spring.application.name=scentcepts
spring.datasource.url=jdbc:postgresql://localhost:5432/scentcepts_db
spring.datasource.username=postgres
spring.datasource.password=2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
