spring.application.name=scentcepts

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/scentcepts_db
        username: your_postgres_user
        password: your_postgres_password
    jpa:
        hibernate:
            ddl-auto: update
    show-sql: true